In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv('customers.csv')

In [3]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5150 non-null   str
 1   customer_name  5150 non-null   str
 2   gender         4948 non-null   str
 3   age            4892 non-null   str
 4   state          5150 non-null   str
 5   city           4995 non-null   str
 6   signup_date    5150 non-null   str
dtypes: str(7)
memory usage: 536.7 KB

In [4]:
customers.head()

  customer_id  customer_name gender   age        state       city signup_date
0      C01142  Customer 1142    NaN  40.0  West Bengal    Kolkata  2022-07-16
1      C02120  Customer 2120      F  63.0        Delhi  New Delhi  2024-05-19
2      C04018  Customer 4018      M  55.0    Karnataka     Mysuru  2022-06-27
3      C01990  Customer 1990      F  49.0  Maharashtra     Nagpur  2023-02-04
4      C04873  Customer 4873      F  24.0     Gujarat       Surat  2024-03-09

In [5]:
# datatypes

In [6]:
df_c = customers.copy()

In [7]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5150 non-null   str
 1   customer_name  5150 non-null   str
 2   gender         4948 non-null   str
 3   age            4892 non-null   str
 4   state          5150 non-null   str
 5   city           4995 non-null   str
 6   signup_date    5150 non-null   str
dtypes: str(7)
memory usage: 536.7 KB

In [8]:
df_c.head()

  customer_id  customer_name gender   age        state       city signup_date
0      C01142  Customer 1142    NaN  40.0  West Bengal    Kolkata  2022-07-16
1      C02120  Customer 2120      F  63.0        Delhi  New Delhi  2024-05-19
2      C04018  Customer 4018      M  55.0    Karnataka     Mysuru  2022-06-27
3      C01990  Customer 1990      F  49.0  Maharashtra     Nagpur  2023-02-04
4      C04873  Customer 4873      F  24.0     Gujarat       Surat  2024-03-09

In [9]:
df_c['age'].unique()

<ArrowStringArray>
[   '40.0',    '63.0',    '55.0',    '49.0',    '24.0',    '64.0',    '38.0',
    '21.0',    '51.0',    '34.0',    '53.0',    '56.0',    '26.0',    '36.0',
    '54.0',    '27.0',    '30.0',    '42.0',    '62.0',    '41.0',    '44.0',
    '67.0',    '31.0',    '50.0',    '18.0',    '48.0',    '66.0',    '39.0',
    '47.0',    '69.0',       nan,    '57.0',    '29.0',    '35.0',    '20.0',
    '23.0',    '25.0',    '33.0',    '22.0',    '68.0',    '45.0',    '52.0',
    '46.0',    '37.0',    '65.0',    '19.0',    '59.0',    '32.0',    '61.0',
      '-5',    '28.0',    '60.0',    '58.0',    '43.0', 'unknown',     '150']
Length: 56, dtype: str

In [10]:
customers.isna().sum()

customer_id        0
customer_name      0
gender           202
age              258
state              0
city             155
signup_date        0
dtype: int64

In [11]:
df_c.isna().sum()

customer_id        0
customer_name      0
gender           202
age              258
state              0
city             155
signup_date        0
dtype: int64

DEALING WITH AGE

In [14]:
df_c['age'] = df_c['age'].replace({'unknown': np.nan})

In [16]:
df_c['age'].unique()

<ArrowStringArray>
['40.0', '63.0', '55.0', '49.0', '24.0', '64.0', '38.0', '21.0', '51.0',
 '34.0', '53.0', '56.0', '26.0', '36.0', '54.0', '27.0', '30.0', '42.0',
 '62.0', '41.0', '44.0', '67.0', '31.0', '50.0', '18.0', '48.0', '66.0',
 '39.0', '47.0', '69.0',    nan, '57.0', '29.0', '35.0', '20.0', '23.0',
 '25.0', '33.0', '22.0', '68.0', '45.0', '52.0', '46.0', '37.0', '65.0',
 '19.0', '59.0', '32.0', '61.0',   '-5', '28.0', '60.0', '58.0', '43.0',
  '150']
Length: 55, dtype: str

In [17]:
df_c['age'].isna().sum()

np.int64(276)

In [19]:
df_c['age'] = pd.to_numeric(df_c['age'])

In [21]:
df_c['age'].unique()

array([ 40.,  63.,  55.,  49.,  24.,  64.,  38.,  21.,  51.,  34.,  53.,
        56.,  26.,  36.,  54.,  27.,  30.,  42.,  62.,  41.,  44.,  67.,
        31.,  50.,  18.,  48.,  66.,  39.,  47.,  69.,  nan,  57.,  29.,
        35.,  20.,  23.,  25.,  33.,  22.,  68.,  45.,  52.,  46.,  37.,
        65.,  19.,  59.,  32.,  61.,  -5.,  28.,  60.,  58.,  43., 150.])

In [24]:
df_c['age'].median()

np.float64(43.0)

In [32]:
df_c['age'] = df_c['age'].fillna(df_c['age'].median())

In [28]:
df_c['age'].unique()

array([ 40.,  63.,  55.,  49.,  24.,  64.,  38.,  21.,  51.,  34.,  53.,
        56.,  26.,  36.,  54.,  27.,  30.,  42.,  62.,  41.,  44.,  67.,
        31.,  50.,  18.,  48.,  66.,  39.,  47.,  69.,  43.,  57.,  29.,
        35.,  20.,  23.,  25.,  33.,  22.,  68.,  45.,  52.,  46.,  37.,
        65.,  19.,  59.,  32.,  61.,  -5.,  28.,  60.,  58., 150.])

In [38]:
df_c['age'] = df_c['age'].replace([150, -5],df_c['age'].median())

In [40]:
df_c['age'].unique()

array([40., 63., 55., 49., 24., 64., 38., 21., 51., 34., 53., 56., 26.,
       36., 54., 27., 30., 42., 62., 41., 44., 67., 31., 50., 18., 48.,
       66., 39., 47., 69., 43., 57., 29., 35., 20., 23., 25., 33., 22.,
       68., 45., 52., 46., 37., 65., 19., 59., 32., 61., 28., 60., 58.])

In [42]:
df_c['age'] = df_c['age'].astype(int)

In [43]:
df_c['age'].unique()

array([40, 63, 55, 49, 24, 64, 38, 21, 51, 34, 53, 56, 26, 36, 54, 27, 30,
       42, 62, 41, 44, 67, 31, 50, 18, 48, 66, 39, 47, 69, 43, 57, 29, 35,
       20, 23, 25, 33, 22, 68, 45, 52, 46, 37, 65, 19, 59, 32, 61, 28, 60,
       58])

In [44]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5150 non-null   str
 1   customer_name  5150 non-null   str
 2   gender         4948 non-null   str
 3   age            5150 non-null   int64
 4   state          5150 non-null   str
 5   city           4995 non-null   str
 6   signup_date    5150 non-null   str
dtypes: int64(1), str(6)
memory usage: 516.9 KB

DEALING WITH GENDER

In [48]:
df_c['gender'].unique()

<ArrowStringArray>
[nan, 'F', 'M', 'Male', 'Female']
Length: 5, dtype: str

In [51]:
df_c['gender'] = df_c['gender'].replace({'F':'Female', 'M':'Male'})

In [52]:
df_c['gender'].unique()

<ArrowStringArray>
[nan, 'Female', 'Male']
Length: 3, dtype: str

In [58]:
df_c['gender'].isna().sum()

np.int64(202)

In [65]:
df_c['gender'] = df_c['gender'].fillna('Unknown')

In [66]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5150 non-null   str
 1   customer_name  5150 non-null   str
 2   gender         5150 non-null   str
 3   age            5150 non-null   int64
 4   state          5150 non-null   str
 5   city           4995 non-null   str
 6   signup_date    5150 non-null   str
dtypes: int64(1), str(6)
memory usage: 534.3 KB

In [67]:
df_c['state'].unique()

<ArrowStringArray>
[    'West Bengal',           'Delhi',       'Karnataka',     'Maharashtra',
       ' Gujarat ',   'Uttar Pradesh',   'UTTAR PRADESH',          'Kerala',
       'Rajasthan',      'Tamil Nadu',       'TELANGANA',         ' Delhi ',
         'Gujarat',           'DELHI',       'Telangana',       'KARNATAKA',
     ' Telangana ',     ' Rajasthan ',     ' Karnataka ',     'MAHARASHTRA',
       'RAJASTHAN', ' Uttar Pradesh ',      'TAMIL NADU',     'WEST BENGAL',
   ' Maharashtra ',         'GUJARAT',    ' Tamil Nadu ',        ' Kerala ',
   ' West Bengal ',          'KERALA']
Length: 30, dtype: str

In [69]:
df_c['state'] = df_c['state'].astype(str).str.strip().str.title()

In [70]:
df_c['state'].unique()

<ArrowStringArray>
[  'West Bengal',         'Delhi',     'Karnataka',   'Maharashtra',
       'Gujarat', 'Uttar Pradesh',        'Kerala',     'Rajasthan',
    'Tamil Nadu',     'Telangana']
Length: 10, dtype: str

In [71]:
df_c['city'].unique()

<ArrowStringArray>
[   'Kolkata',  'New Delhi',     'Mysuru',     'Nagpur',      'Surat',
    'Lucknow',      'Noida',  'Bengaluru',       'Pune',      'Kochi',
     'Jaipur',          nan, 'Coimbatore',    'Chennai',  'Hyderabad',
  'Ahmedabad',     'Mumbai']
Length: 17, dtype: str

In [82]:
df_c[['state', 'city']].drop_duplicates()

              state        city
0       West Bengal     Kolkata
1             Delhi   New Delhi
2         Karnataka      Mysuru
3       Maharashtra      Nagpur
4           Gujarat       Surat
6     Uttar Pradesh     Lucknow
9     Uttar Pradesh       Noida
12        Karnataka   Bengaluru
15      Maharashtra        Pune
20           Kerala       Kochi
21        Rajasthan      Jaipur
22      Maharashtra         NaN
24            Delhi         NaN
25       Tamil Nadu  Coimbatore
26       Tamil Nadu     Chennai
35        Telangana   Hyderabad
43          Gujarat   Ahmedabad
66        Telangana         NaN
76      Maharashtra      Mumbai
108   Uttar Pradesh         NaN
160         Gujarat         NaN
161      Tamil Nadu         NaN
197       Karnataka         NaN
440     West Bengal         NaN
527          Kerala         NaN
1483      Rajasthan         NaN

In [83]:
# now we can se we have delhi with ony new delhi city. so we can fill nan with new delhi.
# but we can also see that there are some state with different citites. so we can't fill those. that's why we're just filling those null values with Unknown

In [85]:
df_c['city'] = df_c['city'].fillna('Unknown')

In [86]:
df_c['city'].unique()

<ArrowStringArray>
[   'Kolkata',  'New Delhi',     'Mysuru',     'Nagpur',      'Surat',
    'Lucknow',      'Noida',  'Bengaluru',       'Pune',      'Kochi',
     'Jaipur',    'Unknown', 'Coimbatore',    'Chennai',  'Hyderabad',
  'Ahmedabad',     'Mumbai']
Length: 17, dtype: str

In [87]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5150 non-null   str
 1   customer_name  5150 non-null   str
 2   gender         5150 non-null   str
 3   age            5150 non-null   int64
 4   state          5150 non-null   str
 5   city           5150 non-null   str
 6   signup_date    5150 non-null   str
dtypes: int64(1), str(6)
memory usage: 534.8 KB

In [90]:
df_c = df_c.drop_duplicates()

In [91]:
df_c.info()

<class 'pandas.DataFrame'>
Index: 5000 entries, 0 to 5149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   str
 1   customer_name  5000 non-null   str
 2   gender         5000 non-null   str
 3   age            5000 non-null   int64
 4   state          5000 non-null   str
 5   city           5000 non-null   str
 6   signup_date    5000 non-null   str
dtypes: int64(1), str(6)
memory usage: 561.2 KB

DEALING WITH SUGNUP DATE

In [93]:
df_c['signup_date'].astype(str).str.replace(r'\d', 'X', regex = True).value_counts()

signup_date
XXXX-XX-XX      4250
XX/XX/XXXX       375
Jan XX, XXXX      48
Jun XX, XXXX      45
Apr XX, XXXX      45
May XX, XXXX      37
Mar XX, XXXX      32
Aug XX, XXXX      29
Jul XX, XXXX      26
Feb XX, XXXX      26
Sep XX, XXXX      24
Oct XX, XXXX      23
Dec XX, XXXX      20
Nov XX, XXXX      20
Name: count, dtype: int64

In [95]:
df_c['signup_date'] = pd.to_datetime(df_c['signup_date'], format = 'mixed')

In [96]:
df_c['signup_date']

0      2022-07-16
1      2024-05-19
2      2022-06-27
3      2023-02-04
4      2024-03-09
          ...
5145   2023-12-07
5146   2023-11-04
5147   2022-01-01
5148   2024-05-03
5149   2023-04-17
Name: signup_date, Length: 5000, dtype: datetime64[us]

In [97]:
df_c.info()

<class 'pandas.DataFrame'>
Index: 5000 entries, 0 to 5149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   str
 1   customer_name  5000 non-null   str
 2   gender         5000 non-null   str
 3   age            5000 non-null   int64
 4   state          5000 non-null   str
 5   city           5000 non-null   str
 6   signup_date    5000 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 511.0 KB

In [99]:
df_c.dtypes

customer_id                 str
customer_name               str
gender                      str
age                       int64
state                       str
city                        str
signup_date      datetime64[us]
dtype: object

In [100]:
df_c.head()

  customer_id  customer_name   gender  age        state       city signup_date
0      C01142  Customer 1142  Unknown   40  West Bengal    Kolkata  2022-07-16
1      C02120  Customer 2120   Female   63        Delhi  New Delhi  2024-05-19
2      C04018  Customer 4018     Male   55    Karnataka     Mysuru  2022-06-27
3      C01990  Customer 1990   Female   49  Maharashtra     Nagpur  2023-02-04
4      C04873  Customer 4873   Female   24      Gujarat      Surat  2024-03-09

In [103]:
df_c.to_csv('customers_clean.csv', index = False)