In [1]:
import pandas as pd
import numpy as np
from dateutil import parser

## CLEANING ORDER TABLE

In [2]:
orders = pd.read_csv('orders.csv')

In [3]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 30900 entries, 0 to 30899
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       30900 non-null  str
 1   customer_id    30296 non-null  str
 2   order_date     30900 non-null  str
 3   product_id     30900 non-null  str
 4   seller_id      30900 non-null  str
 5   quantity       29989 non-null  float64
 6   unit_price     30900 non-null  float64
 7   discount_pct   29662 non-null  float64
 8   sales_amount   30900 non-null  str
 9   cost_amount    30900 non-null  float64
 10  profit         30900 non-null  float64
 11  order_status   30900 non-null  str
 12  shipping_days  29979 non-null  float64
dtypes: float64(6), str(7)
memory usage: 4.5 MB

In [4]:
df_o = orders.copy()

In [6]:
df_o.info()

<class 'pandas.DataFrame'>
RangeIndex: 30900 entries, 0 to 30899
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       30900 non-null  str
 1   customer_id    30296 non-null  str
 2   order_date     30900 non-null  str
 3   product_id     30900 non-null  str
 4   seller_id      30900 non-null  str
 5   quantity       29989 non-null  float64
 6   unit_price     30900 non-null  float64
 7   discount_pct   29662 non-null  float64
 8   sales_amount   30900 non-null  str
 9   cost_amount    30900 non-null  float64
 10  profit         30900 non-null  float64
 11  order_status   30900 non-null  str
 12  shipping_days  29979 non-null  float64
dtypes: float64(6), str(7)
memory usage: 4.5 MB

In [9]:
df_o.duplicated().sum()

np.int64(900)

In [11]:
df_o.isna().sum()

order_id            0
customer_id       604
order_date          0
product_id          0
seller_id           0
quantity          911
unit_price          0
discount_pct     1238
sales_amount        0
cost_amount         0
profit              0
order_status        0
shipping_days     921
dtype: int64

In [14]:
df_o = df_o.drop_duplicates()

In [17]:
#df_o.info()

In [16]:
df_o.isna().sum()

order_id            0
customer_id       589
order_date          0
product_id          0
seller_id           0
quantity          889
unit_price          0
discount_pct     1200
sales_amount        0
cost_amount         0
profit              0
order_status        0
shipping_days     889
dtype: int64

In [18]:
df_o.describe()

,quantity,unit_price,discount_pct,cost_amount,profit,shipping_days
count,29111.000000,30000.000000,28800.000000,30000.000000,30000.000000,29111.000000
mean,6.848889,3138.512179,7.738194,3912.448463,1102.890179,5.402253
std,71.413331,7050.852084,8.418290,11318.390526,2658.427625,2.426732
min,-1.000000,50.910000,0.000000,44.920000,-40519.610000,-3.000000
25%,1.000000,387.820000,0.000000,361.840000,118.600000,3.000000
50%,1.000000,1298.250000,5.000000,832.230000,417.030000,5.000000
75%,2.000000,2441.660000,15.000000,2521.120000,1026.360000,7.000000
max,999.000000,54951.840000,30.000000,232851.050000,51911.300000,9.000000

In [20]:
df_o['unit_price'].isna().sum()

np.int64(0)

In [21]:
# unit price is cleanned and well we can use them accordingly when in need

In [48]:
df_o['discount_pct'].isna().sum()

np.int64(1200)

In [33]:
(df_o['discount_pct'] == 0 ).sum()

np.int64(11574)

In [36]:
(df_o['discount_pct'] != 0 ).sum()
# 11574 are the rows in which we have 0 discounts.
# and 18426 are where 0 is not present

np.int64(18426)

In [37]:
11574 + 18426

30000

In [51]:
(df_o['discount_pct'] == 5 ).sum()

np.int64(4275)

In [52]:
(df_o['discount_pct'] == 10 ).sum()

np.int64(5698)

In [53]:
(df_o['discount_pct'] == 15 ).sum()

np.int64(2871)

In [54]:
(df_o['discount_pct'] == 20 ).sum()

np.int64(3002)

In [56]:
(df_o['discount_pct'] == 30 ).sum()

np.int64(1380)

In [57]:
df_o['discount_pct'].unique()

array([10.,  0., nan, 30.,  5., 20., 15.])

In [58]:
4275 + 5698+2871+3002+1380+11574

28800

In [95]:
# so we have 1200 nuls that we don't know the discount. As we have unit price we can do aomething from that.

In [60]:
df_o.columns

Index(['order_id', 'customer_id', 'order_date', 'product_id', 'seller_id',
       'quantity', 'unit_price', 'discount_pct', 'sales_amount', 'cost_amount',
       'profit', 'order_status', 'shipping_days'],
      dtype='str')

In [61]:
df_o['sales_amount'].isna().sum()

np.int64(0)

In [62]:
df_o.dtypes

order_id             str
customer_id          str
order_date           str
product_id           str
seller_id            str
quantity         float64
unit_price       float64
discount_pct     float64
sales_amount         str
cost_amount      float64
profit           float64
order_status         str
shipping_days    float64
dtype: object

In [66]:
df_o['sales_amount'] = df_o['sales_amount'].str.replace('₹', '').str.replace(',', '').astype(float)

In [67]:
df_o.dtypes

order_id             str
customer_id          str
order_date           str
product_id           str
seller_id            str
quantity         float64
unit_price       float64
discount_pct     float64
sales_amount     float64
cost_amount      float64
profit           float64
order_status         str
shipping_days    float64
dtype: object

In [68]:
df_o['quantity'].isna().sum()

np.int64(889)

In [70]:
df_o['quantity'].unique()

array([  5.,   1.,   3.,   2.,  nan,   4., 999.,  -1.])

In [71]:
(df_o['quantity'] == -1).sum()

np.int64(298)

In [72]:
(df_o['quantity'] == 999).sum()

np.int64(150)

In [82]:
(df_o['quantity'] == 1).sum()

np.int64(17276)

In [83]:
(df_o['quantity'] == 2).sum()

np.int64(5650)

In [84]:
(df_o['quantity'] == 3).sum()

np.int64(2860)

In [85]:
(df_o['quantity'] == 4).sum()

np.int64(1715)

In [86]:
(df_o['quantity'] == 5).sum()

np.int64(1162)

In [87]:
298+150+17276+5650+2860+1715+1162

29111

In [88]:
29111+889

30000

In [89]:
# so in quantity we have 889 null values that are nan, and 150 values 999 and 298 rows of -1

In [90]:
df_o['cost_amount'].unique()

array([ 579.55,  293.04,  115.91, ...,  506.19,  860.4 , 1998.3 ],
      shape=(2435,))

In [91]:
df_o.describe()

,quantity,unit_price,discount_pct,sales_amount,cost_amount,profit,shipping_days
count,29111.000000,30000.000000,28800.000000,30000.000000,30000.000000,30000.000000,29111.000000
mean,6.848889,3138.512179,7.738194,5015.338643,3912.448463,1102.890179,5.402253
std,71.413331,7050.852084,8.418290,13440.659061,11318.390526,2658.427625,2.426732
min,-1.000000,50.910000,0.000000,35.640000,44.920000,-40519.610000,-3.000000
25%,1.000000,387.820000,0.000000,499.680000,361.840000,118.600000,3.000000
50%,1.000000,1298.250000,5.000000,1396.230000,832.230000,417.030000,5.000000
75%,2.000000,2441.660000,15.000000,3679.730000,2521.120000,1026.360000,7.000000
max,999.000000,54951.840000,30.000000,236464.120000,232851.050000,51911.300000,9.000000

In [92]:
df_o['shipping_days'].unique()

array([ 5.,  6.,  9.,  4.,  2., nan,  7.,  3.,  8., -3.])

In [93]:
df_o['shipping_days'].isna().sum()

np.int64(889)

In [94]:
df_o['sales_amount'].isna().sum()

np.int64(0)

In [96]:
df_o['profit'].isna().sum()

np.int64(0)

In [97]:
(df_o['shipping_days'] == -3 ).sum()

np.int64(300)

In [98]:
(df_o['shipping_days'] == 2 ).sum()

np.int64(3617)

In [99]:
(df_o['shipping_days'] == 3 ).sum()

np.int64(3637)

In [100]:
(df_o['shipping_days'] == 4 ).sum()

np.int64(3514)

In [101]:
(df_o['shipping_days'] == 5 ).sum()

np.int64(3589)

In [102]:
(df_o['shipping_days'] == 5 ).sum()

np.int64(3589)

In [103]:
(df_o['shipping_days'] == 6 ).sum()

np.int64(3689)

In [104]:
(df_o['shipping_days'] == 7 ).sum()

np.int64(3698)

In [105]:
(df_o['shipping_days'] == 8 ).sum()

np.int64(3604)

In [106]:
(df_o['shipping_days'] == 9 ).sum()

np.int64(3463)

In [107]:
300+3617+3637+3514+3589+3689+3698+3604+3463

29111

In [108]:
# shipping_days has 300 rows of -3 and 889 rows of nulls

In [111]:
df_o['customer_id'].unique()

<ArrowStringArray>
['C01720', 'C04502', 'C03849', 'C01368', 'C00041', 'C00504', 'C02901',
 'C04176', 'C04427', 'C03709',
 ...
 'C00970', 'C02344', 'C03796', 'C04894', 'C02621', 'C03644', 'C03330',
 'C02514', 'C03982', 'C04116']
Length: 4641, dtype: str

In [112]:
customers = pd.read_csv('customers.csv')

In [116]:
df_c = customers.copy()

In [117]:
df_c['customer_id'].info()

<class 'pandas.Series'>
RangeIndex: 5150 entries, 0 to 5149
Series name: customer_id
Non-Null Count  Dtype
--------------  -----
5150 non-null   str
dtypes: str(1)
memory usage: 70.5 KB

In [125]:
df_o.loc[df_o['customer_id'].isin(df_c['customer_id']), 'customer_id']

0        C01720
1        C04502
2        C03849
3        C01368
4        C00041
          ...
30895    C00756
30896    C01759
30897    C04116
30898    C04786
30899    C04165
Name: customer_id, Length: 29111, dtype: str

In [127]:
df_o.loc[~df_o['customer_id'].isin(df_c['customer_id']), 'customer_id']

25          NaN
137         NaN
160      C99999
181         NaN
188      C99999
          ...
30760       NaN
30768       NaN
30778    C99999
30840       NaN
30867       NaN
Name: customer_id, Length: 889, dtype: str

In [128]:
df_o.loc[~df_o['customer_id'].isin(df_c['customer_id']), 'customer_id'].value_counts()

customer_id
C99999    300
Name: count, dtype: int64

In [129]:
df_c['customer_id'] = df_c['customer_id'].astype(str).str.strip()

In [130]:
df_o['customer_id'] = df_o['customer_id'].astype(str).str.strip()

In [131]:
df_o.loc[~df_o['customer_id'].isin(df_c['customer_id']), 'customer_id'].value_counts()

customer_id
C99999    300
Name: count, dtype: int64

In [132]:
df_o.loc[~df_o['customer_id'].isin(df_c['customer_id']), 'customer_id'] = np.nan

In [133]:
df_o['customer_id'].isna().sum()

np.int64(889)

In [135]:
df_o[['quantity', 'unit_price', 'sales_amount','cost_amount', 'discount_pct', 'profit']].head()

   quantity  unit_price  sales_amount  cost_amount  discount_pct  profit
0       5.0      153.74        691.83       579.55          10.0  112.28
1       1.0      418.61        418.61       293.04           0.0  125.57
2       1.0      153.74        153.74       115.91           NaN   37.83
3       1.0     1469.72       1322.75       832.23          10.0  490.52
4       3.0      525.70       1577.10      1113.24           0.0  463.86

In [136]:
df_o.dtypes

order_id             str
customer_id          str
order_date           str
product_id           str
seller_id            str
quantity         float64
unit_price       float64
discount_pct     float64
sales_amount     float64
cost_amount      float64
profit           float64
order_status         str
shipping_days    float64
dtype: object

In [140]:
#pd.to_datetime(df_o['order_date'])

In [141]:
#so lets find all formats that my column has

In [142]:
df_o['order_date'].astype(str).str.replace(r"\d", "X", regex = True).value_counts()

order_date
XXXX-XX-XX      24000
XX/XX/XXXX       3000
Dec XX, XXXX     1220
Aug XX, XXXX      205
Sep XX, XXXX      203
Oct XX, XXXX      186
Nov XX, XXXX      185
May XX, XXXX      167
Jul XX, XXXX      167
Jun XX, XXXX      152
Apr XX, XXXX      143
Mar XX, XXXX      129
Jan XX, XXXX      127
Feb XX, XXXX      116
Name: count, dtype: int64

In [144]:
# we can use this also.
df_o['order_date'] = pd.to_datetime(df_o['order_date'], format = 'mixed', errors = 'coerce')

In [146]:
df_o.info()

<class 'pandas.DataFrame'>
Index: 30000 entries, 0 to 30899
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       30000 non-null  str
 1   customer_id    29111 non-null  str
 2   order_date     30000 non-null  datetime64[us]
 3   product_id     30000 non-null  str
 4   seller_id      30000 non-null  str
 5   quantity       29111 non-null  float64
 6   unit_price     30000 non-null  float64
 7   discount_pct   28800 non-null  float64
 8   sales_amount   30000 non-null  float64
 9   cost_amount    30000 non-null  float64
 10  profit         30000 non-null  float64
 11  order_status   30000 non-null  str
 12  shipping_days  29111 non-null  float64
dtypes: datetime64[us](1), float64(7), str(5)
memory usage: 4.1 MB

In [153]:
df_o[['quantity', 'unit_price', 'sales_amount','cost_amount', 'discount_pct', 'profit']].head()

   quantity  unit_price  sales_amount  cost_amount  discount_pct  profit
0       5.0      153.74        691.83       579.55          10.0  112.28
1       1.0      418.61        418.61       293.04           0.0  125.57
2       1.0      153.74        153.74       115.91           NaN   37.83
3       1.0     1469.72       1322.75       832.23          10.0  490.52
4       3.0      525.70       1577.10      1113.24           0.0  463.86

In [148]:
df_o[['quantity', 'unit_price', 'sales_amount','cost_amount', 'discount_pct', 'profit']].isna().sum()

quantity         889
unit_price         0
sales_amount       0
cost_amount        0
discount_pct    1200
profit             0
dtype: int64

In [150]:
# missing values don't mean you have to dlete those rows

In [154]:

# as we can see quantity and discount have nulls so may be at some rows there will both rows nulls. if yes then we can't calculate them.

In [155]:
df_o[['quantity', 'discount_pct']].isna().sum()

quantity         889
discount_pct    1200
dtype: int64

In [157]:
df_o[df_o['quantity'].isna() & df_o['discount_pct'].isna()]

,order_id,customer_id,order_date,product_id,seller_id,quantity,unit_price,discount_pct,sales_amount,cost_amount,profit,order_status,shipping_days
167,O004387,C01766,2023-01-01,P0065,S0051,NaN,3639.66,NaN,8735.18,7233.24,1501.94,Cancelled,4.0
248,O021975,C04391,2023-01-26,P0548,S0128,NaN,1601.79,NaN,1441.61,943.49,498.12,Cancelled,7.0
2368,O027315,C03709,2023-10-25,P0326,S0144,NaN,539.65,NaN,512.67,328.40,184.27,Cancelled,5.0
2422,O028545,C03483,2024-06-26,P0457,S0086,NaN,449.16,NaN,381.79,295.30,86.49,DELIVERED,4.0
3024,O007451,NaN,2024-02-07,P0088,S0120,NaN,341.71,NaN,307.54,193.10,114.44,Deliverd,3.0
3353,O010810,C03577,2023-10-27,P0085,S0024,NaN,1845.33,NaN,1845.33,1499.39,345.94,Deliverd,3.0
3938,O026814,C01068,2024-01-18,P0124,S0013,NaN,176.94,NaN,176.94,130.70,46.24,Delivered,4.0
4445,O021036,C04427,2024-12-31,P0022,S0004,NaN,2638.26,NaN,5012.69,4244.00,768.69,DELIVERED,8.0
4869,O029944,C02921,2024-10-07,P0302,S0064,NaN,607.70,NaN,607.70,251.87,355.83,Deliverd,6.0
5775,O011167,C01759,2024-06-10,P0277,S0022,NaN,2075.35,NaN,1867.82,1570.09,297.73,Deliverd,6.0
5799,O021340,C01466,2022-11-27,P0542,S0200,NaN,1289.37,NaN,2062.99,1571.94,491.05,DELIVERED,3.0
7032,O000447,C04427,2024-12-31,P0027,S0163,NaN,591.84,NaN,1183.68,778.58,405.10,Deliverd,3.0
8661,O012184,C01558,2024-10-23,P0419,S0164,NaN,1469.72,NaN,6613.74,4161.15,2452.59,Deliverd,3.0
8679,O016103,C03596,2024-12-31,P0088,S0120,NaN,341.71,NaN,239.20,193.10,46.10,Deliverd,9.0
10080,O021305,C03622,2024-12-31,P0419,S0164,NaN,1469.72,NaN,1469.72,832.23,637.49,Deliverd,5.0
14620,O013387,C02324,2023-07-16,P0253,S0045,NaN,1068.79,NaN,1068.79,522.64,546.15,Cancelled,4.0
16394,O025614,C04844,2022-08-27,P0578,S0113,NaN,444.73,NaN,444.73,317.92,126.81,Deliverd,9.0
19075,O014299,C03281,2022-07-25,P0088,S0120,NaN,341.71,NaN,615.08,386.20,228.88,Delivered,5.0
19095,O019650,C00556,2022-09-27,P0419,S0164,NaN,1469.72,NaN,2498.52,1664.46,834.06,Deliverd,5.0
19570,O024671,C00909,2024-12-31,P0079,S0057,NaN,277.72,NaN,1110.88,797.64,313.24,Deliverd,5.0
21297,O026933,C02647,2024-01-02,P0512,S0057,NaN,623.23,NaN,560.91,365.70,195.21,Deliverd,8.0
21565,O008294,C00575,2022-12-24,P0242,S0034,NaN,155.35,NaN,155.35,132.14,23.21,Deliverd,5.0
21769,O000719,C03432,2024-12-31,P0371,S0163,NaN,713.78,NaN,642.40,499.40,143.00,Deliverd,5.0
21937,O028462,C02543,2024-09-22,P0359,S0142,NaN,630.85,NaN,567.76,436.93,130.83,Deliverd,9.0
22785,O004310,C02532,2024-01-20,P0419,S0164,NaN,1469.72,NaN,1469.72,832.23,637.49,DELIVERED,9.0
23963,O024637,C04724,2024-03-04,P0290,S0077,NaN,1423.63,NaN,1138.90,845.08,293.82,Deliverd,4.0
25284,O029059,C01467,2022-08-24,P0419,S0164,NaN,1469.72,NaN,5290.99,3328.92,1962.07,Deliverd,NaN
27272,O012848,C02981,2024-12-18,P0395,S0134,NaN,343.29,NaN,291.80,244.72,47.08,Delivered,9.0
27416,O007595,C01341,2024-03-10,P0120,S0168,NaN,2888.70,NaN,2455.40,1760.61,694.79,Delivered,3.0
27826,O004751,C03346,2024-12-31,P0277,S0022,NaN,2075.35,NaN,6226.05,4710.27,1515.78,Deliverd,3.0
28749,O019718,C01544,2024-12-31,P0541,S0194,NaN,10465.63,NaN,10465.63,6013.39,4452.24,Deliverd,NaN
29210,O007342,NaN,2024-11-27,P0508,S0027,NaN,436.18,NaN,370.75,351.00,19.75,Deliverd,8.0
29224,O020508,C01759,2024-07-01,P0406,S0048,NaN,1537.50,NaN,1537.50,894.06,643.44,Deliverd,2.0
30454,O015767,C00610,2024-05-30,P0419,S0164,NaN,1469.72,NaN,1175.78,832.23,343.55,Deliverd,4.0
30559,O025927,C02693,2024-07-19,P0048,S0153,NaN,767.12,NaN,652.05,523.45,128.60,Deliverd,4.0

In [158]:
(df_o['quantity'].isna() & df_o['discount_pct'].isna()).sum()

np.int64(35)

In [159]:
pd.crosstab(
    df_o['quantity'].isna(),
    df_o['discount_pct'].isna()
)

discount_pct  False  True
quantity
False         27946   1165
True            854     35

In [160]:
df_o.rename(columns ={'unit_price':'list_price'}, inplace = True)

In [161]:
df_o.info()

<class 'pandas.DataFrame'>
Index: 30000 entries, 0 to 30899
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       30000 non-null  str
 1   customer_id    29111 non-null  str
 2   order_date     30000 non-null  datetime64[us]
 3   product_id     30000 non-null  str
 4   seller_id      30000 non-null  str
 5   quantity       29111 non-null  float64
 6   list_price     30000 non-null  float64
 7   discount_pct   28800 non-null  float64
 8   sales_amount   30000 non-null  float64
 9   cost_amount    30000 non-null  float64
 10  profit         30000 non-null  float64
 11  order_status   30000 non-null  str
 12  shipping_days  29111 non-null  float64
dtypes: datetime64[us](1), float64(7), str(5)
memory usage: 4.1 MB

In [173]:
(df_o['quantity'].isna() & df_o['discount_pct'].isna()).sum()

np.int64(35)

In [172]:
mask = df_o['quantity'].isna() & df_o['discount_pct'].isna()

df_o.loc[mask, ['list_price', 'sales_amount', 'cost_amount', 'profit', 'order_status']]

       list_price  sales_amount  cost_amount   profit order_status
167       3639.66       8735.18      7233.24  1501.94    Cancelled
248       1601.79       1441.61       943.49   498.12    Cancelled
2368       539.65        512.67       328.40   184.27    Cancelled
2422       449.16        381.79       295.30    86.49    Delivered
3024       341.71        307.54       193.10   114.44    Delivered
3353      1845.33       1845.33      1499.39   345.94    Delivered
3938       176.94        176.94       130.70    46.24    Delivered
4445      2638.26       5012.69      4244.00   768.69    Delivered
4869       607.70        607.70       251.87   355.83    Delivered
5775      2075.35       1867.82      1570.09   297.73    Delivered
5799      1289.37       2062.99      1571.94   491.05    Delivered
7032       591.84       1183.68       778.58   405.10    Delivered
8661      1469.72       6613.74      4161.15  2452.59    Delivered
8679       341.71        239.20       193.10    46.10    Delivered
10080     1469.72       1469.72       832.23   637.49    Delivered
14620     1068.79       1068.79       522.64   546.15    Cancelled
16394      444.73        444.73       317.92   126.81    Delivered
19075      341.71        615.08       386.20   228.88    Delivered
19095     1469.72       2498.52      1664.46   834.06    Delivered
19570      277.72       1110.88       797.64   313.24    Delivered
21297      623.23        560.91       365.70   195.21    Delivered
21565      155.35        155.35       132.14    23.21    Delivered
21769      713.78        642.40       499.40   143.00    Delivered
21937      630.85        567.76       436.93   130.83    Delivered
22785     1469.72       1469.72       832.23   637.49    Delivered
23963     1423.63       1138.90       845.08   293.82    Delivered
25284     1469.72       5290.99      3328.92  1962.07    Delivered
27272      343.29        291.80       244.72    47.08    Delivered
27416     2888.70       2455.40      1760.61   694.79    Delivered
27826     2075.35       6226.05      4710.27  1515.78    Delivered
28749    10465.63      10465.63      6013.39  4452.24    Delivered
29210      436.18        370.75       351.00    19.75    Delivered
29224     1537.50       1537.50       894.06   643.44    Delivered
30454     1469.72       1175.78       832.23   343.55    Delivered
30559      767.12        652.05       523.45   128.60    Delivered

In [174]:
df_o.loc[mask, 'order_status'].value_counts(dropna = False)

order_status
Delivered    31
Cancelled     4
Name: count, dtype: int64

In [170]:
df_o['order_status'] = df_o['order_status'].replace({'Deliverd': 'Delivered'}).astype(str).str.strip().str.title()

In [171]:
df_o['order_status'].unique()

<ArrowStringArray>
['Delivered', 'Cancelled', 'Shipped']
Length: 3, dtype: str

In [175]:
df_o = df_o.drop(index = df_o.index[mask])

In [177]:
(df_o['quantity'].isna() & df_o['discount_pct'].isna()).sum()

np.int64(0)

In [178]:
df_o[['quantity', 'discount_pct']].isna().sum()

quantity         854
discount_pct    1165
dtype: int64

In [179]:
df_o.info()

<class 'pandas.DataFrame'>
Index: 29965 entries, 0 to 30899
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       29965 non-null  str
 1   customer_id    29078 non-null  str
 2   order_date     29965 non-null  datetime64[us]
 3   product_id     29965 non-null  str
 4   seller_id      29965 non-null  str
 5   quantity       29111 non-null  float64
 6   list_price     29965 non-null  float64
 7   discount_pct   28800 non-null  float64
 8   sales_amount   29965 non-null  float64
 9   cost_amount    29965 non-null  float64
 10  profit         29965 non-null  float64
 11  order_status   29965 non-null  str
 12  shipping_days  29078 non-null  float64
dtypes: datetime64[us](1), float64(7), str(5)
memory usage: 4.1 MB

In [180]:
df_o.isna().sum()

order_id            0
customer_id       887
order_date          0
product_id          0
seller_id           0
quantity          854
list_price          0
discount_pct     1165
sales_amount        0
cost_amount         0
profit              0
order_status        0
shipping_days     887
dtype: int64

In [181]:
df_o.duplicated().sum()

np.int64(0)

In [182]:
df_o.shape

(29965, 13)

In [184]:
df_o.loc[df_o['shipping_days'].isna(), 'order_status'].value_counts()

order_status
Delivered    789
Cancelled     73
Shipped       25
Name: count, dtype: int64

In [185]:
df_o.columns

Index(['order_id', 'customer_id', 'order_date', 'product_id', 'seller_id',
       'quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount',
       'profit', 'order_status', 'shipping_days'],
      dtype='str')

In [186]:
df_o.describe()

,order_date,quantity,list_price,discount_pct,sales_amount,cost_amount,profit,shipping_days
count,29965,29111.000000,29965.000000,28800.000000,29965.000000,29965.000000,29965.000000,29078.00000
mean,2024-04-28 07:27:44.301685,6.848889,3140.537795,7.738194,5018.820680,3915.360198,1103.460483,5.40240
min,2022-01-05 00:00:00,-1.000000,50.910000,0.000000,35.640000,44.920000,-40519.610000,-3.00000
25%,2023-10-23 00:00:00,1.000000,387.820000,0.000000,499.680000,361.840000,118.600000,3.00000
50%,2024-07-25 00:00:00,1.000000,1298.250000,5.000000,1396.230000,832.230000,417.030000,5.00000
75%,2024-12-31 00:00:00,2.000000,2441.660000,15.000000,3679.730000,2521.120000,1028.470000,7.00000
max,2024-12-31 00:00:00,999.000000,54951.840000,30.000000,236464.120000,232851.050000,51911.300000,9.00000
std,NaN,71.413331,7054.464363,8.418290,13447.849018,11324.520046,2659.765355,2.42701

In [187]:
df_o[df_o['quantity'] == -1]['order_status'].value_counts()

order_status
Delivered    264
Cancelled     28
Shipped        6
Name: count, dtype: int64

In [188]:
df_o[df_o['quantity'] == 999]['order_status'].value_counts()

order_status
Delivered    134
Cancelled      9
Shipped        7
Name: count, dtype: int64

In [190]:
df_o[df_o['quantity'] == -1][['quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount', 'profit', 'order_status']].head(20)

,quantity,list_price,discount_pct,sales_amount,cost_amount,profit,order_status
128,-1.0,502.68,0.0,502.68,272.25,230.43,Delivered
183,-1.0,576.55,0.0,1729.65,717.51,1012.14,Delivered
236,-1.0,1405.25,10.0,2529.45,1495.70,1033.75,Delivered
290,-1.0,2418.73,0.0,2418.73,1316.33,1102.40,Delivered
494,-1.0,262.42,20.0,209.94,167.22,42.72,Delivered
501,-1.0,277.72,0.0,277.72,199.41,78.31,Delivered
597,-1.0,713.78,5.0,2712.36,1997.60,714.76,Delivered
598,-1.0,3831.50,20.0,3065.20,2988.82,76.38,Delivered
874,-1.0,195.37,0.0,781.48,663.92,117.56,Delivered
1193,-1.0,1469.72,0.0,4409.16,2496.69,1912.47,Delivered
1371,-1.0,153.74,0.0,153.74,115.91,37.83,Delivered
1376,-1.0,153.74,0.0,153.74,115.91,37.83,Delivered
1440,-1.0,153.74,0.0,461.22,347.73,113.49,Delivered
1450,-1.0,166.04,15.0,141.13,93.95,47.18,Delivered
1467,-1.0,690.62,0.0,2071.86,1399.35,672.51,Cancelled
1598,-1.0,1841.18,0.0,1841.18,1318.29,522.89,Delivered
1634,-1.0,160.37,0.0,160.37,129.09,31.28,Delivered
1865,-1.0,903.90,5.0,858.70,465.02,393.68,Delivered
1986,-1.0,546.16,15.0,1392.71,1182.06,210.65,Delivered
2383,-1.0,153.74,10.0,276.73,231.82,44.91,Delivered

In [191]:
df_o[df_o['quantity'] == 999][['quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount', 'profit', 'order_status']].head(20)

,quantity,list_price,discount_pct,sales_amount,cost_amount,profit,order_status
56,999.0,8592.35,10.0,15466.23,12751.34,2714.89,Delivered
536,999.0,1483.50,0.0,5934.00,3752.48,2181.52,Delivered
601,999.0,2627.36,15.0,2233.26,1958.87,274.39,Delivered
656,999.0,1469.72,0.0,2939.44,1664.46,1274.98,Delivered
978,999.0,153.74,0.0,307.48,231.82,75.66,Cancelled
1189,999.0,205.69,5.0,195.41,177.12,18.29,Delivered
1278,999.0,6240.86,10.0,5616.77,5033.07,583.70,Delivered
1353,999.0,878.09,20.0,702.47,391.79,310.68,Delivered
1528,999.0,1719.22,0.0,1719.22,748.55,970.67,Delivered
2157,999.0,243.95,20.0,780.64,785.48,-4.84,Delivered
2542,999.0,423.13,10.0,380.82,272.48,108.34,Shipped
2751,999.0,4016.06,0.0,16064.24,10187.32,5876.92,Delivered
2882,999.0,1469.72,10.0,1322.75,832.23,490.52,Delivered
3085,999.0,591.84,10.0,532.66,389.29,143.37,Delivered
3284,999.0,153.74,0.0,153.74,115.91,37.83,Delivered
3745,999.0,1469.72,0.0,1469.72,832.23,637.49,Delivered
3818,999.0,341.71,10.0,307.54,193.10,114.44,Delivered
3885,999.0,341.71,0.0,341.71,193.10,148.61,Delivered
3899,999.0,153.74,0.0,307.48,231.82,75.66,Delivered
4089,999.0,2441.66,0.0,2441.66,1484.63,957.03,Delivered

In [192]:
df_o['quantity'].value_counts().sort_index()

quantity
-1.0        298
 1.0      17276
 2.0       5650
 3.0       2860
 4.0       1715
 5.0       1162
 999.0      150
Name: count, dtype: int64

In [194]:
df_o[df_o['quantity'].isin([-1, 999])][['quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount', 'profit', 'order_status']].describe()

,quantity,list_price,discount_pct,sales_amount,cost_amount,profit
count,448.000000,448.000000,434.000000,448.000000,448.000000,448.000000
mean,333.821429,2647.780670,7.235023,4143.272031,3121.583884,1021.688147
std,472.455591,6077.448348,8.174204,9842.275900,8568.411937,2053.791296
min,-1.000000,56.400000,0.000000,56.400000,49.550000,-6800.180000
25%,-1.000000,341.710000,0.000000,439.710000,283.060000,114.202500
50%,-1.000000,878.090000,5.000000,1371.475000,832.230000,434.810000
75%,999.000000,2367.657500,10.000000,3470.435000,2496.690000,1045.497500
max,999.000000,49587.620000,30.000000,104134.000000,110934.180000,18281.880000

In [195]:
df_o[df_o['quantity'].isin([-1, 999])][['list_price', 'discount_pct', 'sales_amount', 'cost_amount', 'profit']].isna().sum()

list_price       0
discount_pct    14
sales_amount     0
cost_amount      0
profit           0
dtype: int64

In [196]:
df_o[df_o['quantity'].isin([-1, 999]) & df_o['discount_pct'].isna()][['quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount', 'profit', 'order_status']]

,quantity,list_price,discount_pct,sales_amount,cost_amount,profit,order_status
4526,-1.0,2814.00,NaN,2814.00,2098.97,715.03,Delivered
5361,999.0,4016.06,NaN,3815.26,2546.83,1268.43,Delivered
5431,-1.0,525.70,NaN,2365.65,1855.40,510.25,Delivered
8837,999.0,259.17,NaN,220.29,173.02,47.27,Delivered
9302,-1.0,444.73,NaN,355.78,317.92,37.86,Cancelled
9343,999.0,480.24,NaN,1920.96,1256.52,664.44,Shipped
10026,-1.0,153.74,NaN,153.74,115.91,37.83,Cancelled
14142,-1.0,341.71,NaN,341.71,193.10,148.61,Delivered
14684,-1.0,3828.31,NaN,3636.89,2744.65,892.24,Delivered
19791,-1.0,14920.74,NaN,13428.67,10500.22,2928.45,Delivered
23736,-1.0,2359.45,NaN,4482.95,3087.10,1395.85,Delivered
24417,-1.0,259.17,NaN,220.29,173.02,47.27,Delivered
25377,-1.0,8592.35,NaN,16325.46,12751.34,3574.12,Delivered
25825,999.0,1469.72,NaN,4703.10,3328.92,1374.18,Delivered

In [198]:
# we can't calculate these rows. because of anomalies  quantity and discount missing.

In [200]:
df_o = df_o.drop(df_o[df_o['quantity'].isin([-1, 999]) & df_o['discount_pct'].isna()].index)

In [201]:
df_o.shape

(29951, 13)

In [202]:
df_o.head()

,order_id,customer_id,order_date,product_id,seller_id,quantity,list_price,discount_pct,sales_amount,cost_amount,profit,order_status,shipping_days
0,O008252,C01720,2023-11-16,P0072,S0056,5.0,153.74,10.0,691.83,579.55,112.28,Delivered,5.0
1,O019782,C04502,2024-08-24,P0316,S0117,1.0,418.61,0.0,418.61,293.04,125.57,Delivered,6.0
2,O027337,C03849,2024-12-31,P0072,S0056,1.0,153.74,NaN,153.74,115.91,37.83,Cancelled,6.0
3,O025510,C01368,2023-11-30,P0419,S0164,1.0,1469.72,10.0,1322.75,832.23,490.52,Delivered,9.0
4,O000483,C00041,2024-08-10,P0539,S0141,3.0,525.70,0.0,1577.10,1113.24,463.86,Delivered,4.0

In [203]:
df_o.describe()

,order_date,quantity,list_price,discount_pct,sales_amount,cost_amount,profit,shipping_days
count,29951,29097.000000,29951.000000,28800.000000,29951.000000,29951.000000,29951.000000,29065.000000
mean,2024-04-28 07:30:38.402724,6.715194,3140.654734,7.738194,5019.337483,3915.816681,1103.520802,5.402236
min,2022-01-05 00:00:00,-1.000000,50.910000,0.000000,35.640000,44.920000,-40519.610000,-3.000000
25%,2023-10-23 00:00:00,1.000000,387.820000,0.000000,499.680000,361.840000,118.600000,3.000000
50%,2024-07-25 00:00:00,1.000000,1298.250000,5.000000,1396.230000,832.230000,417.030000,5.000000
75%,2024-12-31 00:00:00,2.000000,2441.660000,15.000000,3679.730000,2521.120000,1028.470000,7.000000
max,2024-12-31 00:00:00,999.000000,54951.840000,30.000000,236464.120000,232851.050000,51911.300000,9.000000
std,NaN,70.476608,7055.574010,8.418290,13450.573258,11326.857659,2660.287938,2.427155

In [204]:
df_o[df_o['shipping_days']<0]['shipping_days'].value_counts().sort_index()

shipping_days
-3.0    300
Name: count, dtype: int64

In [205]:
df_o[df_o['shipping_days']<0][['order_id','order_date', 'shipping_days', 'order_status']]

      order_id order_date  shipping_days order_status
233    O023642 2024-12-31           -3.0    Delivered
238    O020106 2024-08-01           -3.0    Delivered
293    O016728 2024-06-23           -3.0    Delivered
329    O021249 2023-07-19           -3.0    Delivered
376    O000528 2024-12-31           -3.0    Delivered
...        ...        ...            ...          ...
30362  O020119 2024-12-31           -3.0    Delivered
30415  O013955 2024-12-31           -3.0    Delivered
30475  O004065 2024-09-11           -3.0    Delivered
30747  O017274 2023-03-13           -3.0    Delivered
30840  O012804 2024-12-31           -3.0    Delivered

[300 rows x 4 columns]

In [206]:
df_o[df_o['shipping_days'] == -3 ]['order_status'].value_counts()

order_status
Delivered    271
Cancelled     21
Shipped        8
Name: count, dtype: int64

In [207]:
df_o.loc[df_o['shipping_days'] < 0 , 'shipping_days'] = np.nan

In [208]:
df_o['shipping_days'].isna().sum()

np.int64(1186)

In [209]:
df_o[df_o['shipping_days'].isna()]['order_status'].value_counts()

order_status
Delivered    1059
Cancelled      94
Shipped        33
Name: count, dtype: int64

In [210]:
df_o.info()

<class 'pandas.DataFrame'>
Index: 29951 entries, 0 to 30899
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       29951 non-null  str
 1   customer_id    29065 non-null  str
 2   order_date     29951 non-null  datetime64[us]
 3   product_id     29951 non-null  str
 4   seller_id      29951 non-null  str
 5   quantity       29097 non-null  float64
 6   list_price     29951 non-null  float64
 7   discount_pct   28800 non-null  float64
 8   sales_amount   29951 non-null  float64
 9   cost_amount    29951 non-null  float64
 10  profit         29951 non-null  float64
 11  order_status   29951 non-null  str
 12  shipping_days  28765 non-null  float64
dtypes: datetime64[us](1), float64(7), str(5)
memory usage: 4.1 MB

In [211]:
df_o.isna().sum()

order_id            0
customer_id       886
order_date          0
product_id          0
seller_id           0
quantity          854
list_price          0
discount_pct     1151
sales_amount        0
cost_amount         0
profit              0
order_status        0
shipping_days    1186
dtype: int64

In [213]:
# we can fill shipping days with meaian:

In [214]:
df_o.groupby('order_status')['shipping_days'].median()

order_status
Cancelled    6.0
Delivered    6.0
Shipped      5.0
Name: shipping_days, dtype: float64

In [216]:
df_o['shipping_days'] = df_o['shipping_days'].fillna(df_o.groupby('order_status')['shipping_days'].transform('median'))

In [217]:
df_o.info()

<class 'pandas.DataFrame'>
Index: 29951 entries, 0 to 30899
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       29951 non-null  str
 1   customer_id    29065 non-null  str
 2   order_date     29951 non-null  datetime64[us]
 3   product_id     29951 non-null  str
 4   seller_id      29951 non-null  str
 5   quantity       29097 non-null  float64
 6   list_price     29951 non-null  float64
 7   discount_pct   28800 non-null  float64
 8   sales_amount   29951 non-null  float64
 9   cost_amount    29951 non-null  float64
 10  profit         29951 non-null  float64
 11  order_status   29951 non-null  str
 12  shipping_days  29951 non-null  float64
dtypes: datetime64[us](1), float64(7), str(5)
memory usage: 4.1 MB

In [219]:
#(df_o['sales_amount'] / (df_o['unit_price']* (df_o['discount_pct']/100))).round()

In [223]:
m = (df_o["discount_pct"].isna() & df_o["quantity"].between(1, 10))

df_o.loc[m, "discount_pct"] = (1- (df_o.loc[m, "sales_amount"]/ (df_o.loc[m, "quantity"] * df_o.loc[m, "list_price"] ))) * 100

df_o.loc[m, "discount_pct"] = (df_o.loc[m, "discount_pct"].round().clip(0, 30))

In [224]:
df_o['discount_pct'].isna().sum()

np.int64(0)

In [228]:
bad = ~df_o['quantity'].between(1,10) # rows where quantity is not between 1 and 10

In [229]:
bad.sum()

np.int64(1288)

In [230]:
Sales = df_o.loc[bad, 'sales_amount']
Listed_Price = df_o.loc[bad, 'list_price']
Discount = df_o.loc[bad, 'discount_pct']

In [231]:
Quantity = Sales / (Listed_Price*(1- Discount/100))

In [232]:
Quantity = Quantity.round()

In [234]:
Quantity.unique()

array([1., 3., 2., 5., 4.])

In [235]:
df_o.loc[bad, 'quantity'] = Quantity

In [236]:
df_o['quantity'].value_counts().sort_index()

quantity
1.0    18019
2.0     5930
3.0     2980
4.0     1799
5.0     1223
Name: count, dtype: int64

In [237]:
df_o['quantity'].between(1,10).value_counts()

quantity
True    29951
Name: count, dtype: int64

In [239]:
df_o['discount_pct'].isna().sum()

np.int64(0)

In [241]:
df_o['discount_pct'].unique()

array([10.,  0., 30.,  5., 20., 15.])

In [242]:
df_o['quantity'].unique()

array([5., 1., 3., 2., 4.])

In [243]:
df_o['quantity'] = df_o['quantity'].astype(int)

In [244]:
df_o['discount_pct'] = df_o['discount_pct'].astype(int)

In [245]:
df_o.info()

<class 'pandas.DataFrame'>
Index: 29951 entries, 0 to 30899
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       29951 non-null  str
 1   customer_id    29065 non-null  str
 2   order_date     29951 non-null  datetime64[us]
 3   product_id     29951 non-null  str
 4   seller_id      29951 non-null  str
 5   quantity       29951 non-null  int64
 6   list_price     29951 non-null  float64
 7   discount_pct   29951 non-null  int64
 8   sales_amount   29951 non-null  float64
 9   cost_amount    29951 non-null  float64
 10  profit         29951 non-null  float64
 11  order_status   29951 non-null  str
 12  shipping_days  29951 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(2), str(5)
memory usage: 4.1 MB

In [246]:
df_o.isna().sum()

order_id           0
customer_id      886
order_date         0
product_id         0
seller_id          0
quantity           0
list_price         0
discount_pct       0
sales_amount       0
cost_amount        0
profit             0
order_status       0
shipping_days      0
dtype: int64

NOW WE CAN SAY THAT OUR ORDER TABLE IS CLEANED. IT TAKES MY 3 HRS TO CLEAN IT. 
I USED AI FOR DISCOUNT, AND QUANTITY COLUMNS ONLY. REST I DID MYSELF.

In [248]:
df_o.to_csv('orders_clean.csv', index = False)