In [1]:
import pandas as pd
import numpy as np

In [2]:
payments = pd.read_csv('payments.csv')

In [3]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 30600 entries, 0 to 30599
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      30600 non-null  str
 1   order_id        30600 non-null  str
 2   payment_method  30600 non-null  str
 3   payment_amount  29678 non-null  float64
 4   payment_status  29987 non-null  str
dtypes: float64(1), str(4)
memory usage: 2.0 MB

In [4]:
payments.isna().sum()

payment_id          0
order_id            0
payment_method      0
payment_amount    922
payment_status    613
dtype: int64

In [5]:
payments.head()

  payment_id order_id payment_method  payment_amount payment_status
0  PAY001168  O001168            COD          743.05           Paid
1  PAY007652  O007652    Credit Card         1175.78           Paid
2  PAY023651  O023651            Upi          687.44       Refunded
3  PAY027436  O027436            Upi          341.71           Paid
4  PAY011026  O011026            Upi         1249.26           Paid

In [6]:
df_p = payments.copy()

In [7]:
df_p.info()

<class 'pandas.DataFrame'>
RangeIndex: 30600 entries, 0 to 30599
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      30600 non-null  str
 1   order_id        30600 non-null  str
 2   payment_method  30600 non-null  str
 3   payment_amount  29678 non-null  float64
 4   payment_status  29987 non-null  str
dtypes: float64(1), str(4)
memory usage: 2.0 MB

In [8]:
df_p.dtypes

payment_id            str
order_id              str
payment_method        str
payment_amount    float64
payment_status        str
dtype: object

In [10]:
df_p.duplicated().sum()

np.int64(600)

In [14]:
df_p = df_p.drop_duplicates()

In [15]:
df_p.info()

<class 'pandas.DataFrame'>
Index: 30000 entries, 0 to 30599
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      30000 non-null  str
 1   order_id        30000 non-null  str
 2   payment_method  30000 non-null  str
 3   payment_amount  29100 non-null  float64
 4   payment_status  29400 non-null  str
dtypes: float64(1), str(4)
memory usage: 2.2 MB

In [16]:
df_p['payment_id'].unique()

<ArrowStringArray>
['PAY001168', 'PAY007652', 'PAY023651', 'PAY027436', 'PAY011026', 'PAY027996',
 'PAY014868', 'PAY010928', 'PAY025587', 'PAY018579',
 ...
 'PAY000145', 'PAY021441', 'PAY019280', 'PAY007814', 'PAY010956', 'PAY017290',
 'PAY005193', 'PAY012173', 'PAY000236', 'PAY029734']
Length: 30000, dtype: str

In [18]:
df_p['order_id'].unique()

<ArrowStringArray>
['O001168', 'O007652', 'O023651', 'O027436', 'O011026', 'O027996', 'O014868',
 'O010928', 'O025587', 'O018579',
 ...
 'O000145', 'O021441', 'O019280', 'O007814', 'O010956', 'O017290', 'O005193',
 'O012173', 'O000236', 'O029734']
Length: 30000, dtype: str

In [19]:
df_p['payment_method'].unique()

<ArrowStringArray>
[               'COD',        'Credit Card',                'Upi',
         'Debit Card',                'UPI',   'CASH ON DELIVERY',
             'Wallet',        'CREDIT CARD',        'Net Banking',
       ' Debit Card ',   'Cash on Delivery', ' Cash on Delivery ',
         'DEBIT CARD',        'NET BANKING',              ' UPI ',
      ' Credit Card ',             'WALLET',      ' Net Banking ',
           ' Wallet ']
Length: 19, dtype: str

In [21]:
df_p['payment_method'] = df_p['payment_method'].astype(str).str.strip().str.title()

In [22]:
df_p['payment_method'].unique()

<ArrowStringArray>
[             'Cod',      'Credit Card',              'Upi',
       'Debit Card', 'Cash On Delivery',           'Wallet',
      'Net Banking']
Length: 7, dtype: str

In [23]:
df_p['payment_method'] = df_p['payment_method'].replace({'Cod': 'Cash On Delivery'})

In [24]:
df_p['payment_method'].unique()

<ArrowStringArray>
['Cash On Delivery', 'Credit Card', 'Upi', 'Debit Card', 'Wallet',
 'Net Banking']
Length: 6, dtype: str

In [25]:
df_p.columns

Index(['payment_id', 'order_id', 'payment_method', 'payment_amount',
       'payment_status'],
      dtype='str')

In [27]:
df_p['payment_amount'].unique()

array([ 743.05, 1175.78,  687.44, ..., 8296.58, 3528.95,  624.82],
      shape=(6910,))

In [28]:
df_p['payment_status'].unique()

<ArrowStringArray>
['Paid', 'Refunded', nan]
Length: 3, dtype: str

In [30]:
df_p[['payment_status','payment_method', 'payment_amount']]

      payment_status    payment_method  payment_amount
0               Paid  Cash On Delivery          743.05
1               Paid       Credit Card         1175.78
2           Refunded               Upi          687.44
3               Paid               Upi          341.71
4               Paid               Upi         1249.26
...              ...               ...             ...
30595           Paid       Credit Card          623.07
30596           Paid        Debit Card         1469.72
30597            NaN               Upi          624.82
30598       Refunded       Credit Card         1331.95
30599           Paid        Debit Card        12427.47

[30000 rows x 3 columns]

In [31]:
df_p.describe()

       payment_amount
count    29100.000000
mean      5022.518845
std      13497.078105
min         35.640000
25%        499.420000
50%       1396.230000
75%       3665.660000
max     236464.120000

In [32]:
df_p.isna().sum()

payment_id          0
order_id            0
payment_method      0
payment_amount    900
payment_status    600
dtype: int64

In [33]:
# we can fill payment_amount from order table

In [38]:
df_o = pd.read_csv('orders_clean.csv')

In [39]:
df_o.columns

Index(['order_id', 'customer_id', 'order_date', 'product_id', 'seller_id',
       'quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount',
       'profit', 'order_status', 'shipping_days'],
      dtype='str')

In [40]:
df_o['order_status']

0        Delivered
1        Delivered
2        Cancelled
3        Delivered
4        Delivered
           ...
29946    Delivered
29947    Delivered
29948    Delivered
29949    Cancelled
29950    Delivered
Name: order_status, Length: 29951, dtype: str

In [41]:
df_o['order_status'].unique()

<ArrowStringArray>
['Delivered', 'Cancelled', 'Shipped']
Length: 3, dtype: str

In [42]:
df_p.columns

Index(['payment_id', 'order_id', 'payment_method', 'payment_amount',
       'payment_status'],
      dtype='str')

In [44]:
df_p['payment_status'].unique()

<ArrowStringArray>
['Paid', 'Refunded', nan]
Length: 3, dtype: str

In [45]:
# now we know that if ordered delivered the paymnet is paid. and if canclled payment is refunded .

In [53]:
#preview = df_p.merge(df_o[['order_id', 'order_status', 'sales_amount']], how = 'inner', on = 'order_id')

In [54]:
#preview

In [55]:
#preview = df_p['payment_amount'].fillna(df_o['sales_amount'])

In [56]:
#preview.isna().sum()

In [57]:
df_p = df_p.merge(df_o[['order_id', 'order_status', 'sales_amount']], how = 'inner', on = 'order_id')

In [59]:
df_p.info()

<class 'pandas.DataFrame'>
RangeIndex: 29951 entries, 0 to 29950
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      29951 non-null  str
 1   order_id        29951 non-null  str
 2   payment_method  29951 non-null  str
 3   payment_amount  29052 non-null  float64
 4   payment_status  29352 non-null  str
 5   order_status    29951 non-null  str
 6   sales_amount    29951 non-null  float64
dtypes: float64(2), str(5)
memory usage: 2.7 MB

In [60]:
df_p['payment_amount'] = df_p['payment_amount'].fillna(df_o['sales_amount'])

In [61]:
df_p['payment_status'] = df_p['payment_status'].fillna(df_p['order_status'].map(lambda x : 'Refunded' if x == 'Cancelled' else 'Paid'))

In [62]:
df_p.info()

<class 'pandas.DataFrame'>
RangeIndex: 29951 entries, 0 to 29950
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      29951 non-null  str
 1   order_id        29951 non-null  str
 2   payment_method  29951 non-null  str
 3   payment_amount  29951 non-null  float64
 4   payment_status  29951 non-null  str
 5   order_status    29951 non-null  str
 6   sales_amount    29951 non-null  float64
dtypes: float64(2), str(5)
memory usage: 2.7 MB

In [64]:
df_p.info()

<class 'pandas.DataFrame'>
RangeIndex: 29951 entries, 0 to 29950
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      29951 non-null  str
 1   order_id        29951 non-null  str
 2   payment_method  29951 non-null  str
 3   payment_amount  29951 non-null  float64
 4   payment_status  29951 non-null  str
 5   order_status    29951 non-null  str
 6   sales_amount    29951 non-null  float64
dtypes: float64(2), str(5)
memory usage: 2.7 MB

In [65]:
# now we don't need these 2 columns in payment table, order_status and sales_amount so we can drop them.

In [67]:
df_p = df_p.drop(columns = {'order_status', 'sales_amount'})

In [68]:
df_p.info()

<class 'pandas.DataFrame'>
RangeIndex: 29951 entries, 0 to 29950
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      29951 non-null  str
 1   order_id        29951 non-null  str
 2   payment_method  29951 non-null  str
 3   payment_amount  29951 non-null  float64
 4   payment_status  29951 non-null  str
dtypes: float64(1), str(4)
memory usage: 2.0 MB

In [69]:
df_p.describe()

       payment_amount
count    29951.000000
mean      5012.293706
std      13448.587112
min         35.640000
25%        499.420000
50%       1396.230000
75%       3659.430000
max     236464.120000

In [70]:
df_p.to_csv('payments_clean.csv', index = False)