In [43]:
import pandas as pd
import numpy as np

In [44]:
returns = pd.read_csv('returns.csv')

In [45]:
returns.isna().sum()

return_id          0
order_id           0
product_id         0
return_date        0
return_reason    110
refund_amount     66
dtype: int64

In [46]:
returns.duplicated().sum()

np.int64(63)

In [47]:
df_rt = returns.copy()

In [48]:
df_rt.info()

<class 'pandas.DataFrame'>
RangeIndex: 2156 entries, 0 to 2155
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      2156 non-null   str
 1   order_id       2156 non-null   str
 2   product_id     2156 non-null   str
 3   return_date    2156 non-null   str
 4   return_reason  2046 non-null   str
 5   refund_amount  2090 non-null   float64
dtypes: float64(1), str(5)
memory usage: 190.0 KB

In [49]:
df_rt.duplicated().sum()

np.int64(63)

In [50]:
df_rt = df_rt.drop_duplicates()

In [51]:
df_rt.info()

<class 'pandas.DataFrame'>
Index: 2093 entries, 0 to 2155
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      2093 non-null   str
 1   order_id       2093 non-null   str
 2   product_id     2093 non-null   str
 3   return_date    2093 non-null   str
 4   return_reason  1985 non-null   str
 5   refund_amount  2030 non-null   float64
dtypes: float64(1), str(5)
memory usage: 201.6 KB

In [52]:
df_rt['return_date'] = pd.to_datetime(df_rt['return_date'], format = 'mixed')

In [53]:
df_rt['return_date'].dtypes

dtype('<M8[us]')

In [54]:
df_rt.head()

  return_id order_id product_id return_date   return_reason  refund_amount
0  RET01729  O024764      P0172  2023-07-21  Size/fit issue        2441.66
1  RET01379  O019631      P0206  2024-03-09      Wrong item            NaN
2  RET00985  O013896      P0419  2023-10-19      defective         1469.72
3  RET00242  O003589      P0339  2025-01-15      defective         9756.60
4  RET00135  O002037      P0172  2023-05-16      defective             NaN

In [55]:
df_rt['return_reason'].unique()

<ArrowStringArray>
[    'Size/fit issue',         'Wrong item',         'defective ',
        ' Defective ',       'Changed mind',                  nan,
 ' Not as described ',   'Not as described',          'DEFECTIVE',
   'NOT AS DESCRIBED',     ' Changed mind ',          'Defective',
   ' Size/fit issue ',       'CHANGED MIND',         'WRONG ITEM',
              ' nan ',                'NAN',     'SIZE/FIT ISSUE',
       ' Wrong item ']
Length: 19, dtype: str

In [56]:
df_rt['return_reason'] = df_rt['return_reason'].astype(str).str.strip().str.title().replace({'Nan': np.nan})

In [57]:
df_rt['return_reason'].unique()

<ArrowStringArray>
[  'Size/Fit Issue',       'Wrong Item',        'Defective',
     'Changed Mind',                nan, 'Not As Described']
Length: 6, dtype: str

In [58]:
df_rt['return_reason'].isna().sum()

np.int64(126)

In [59]:
df_rt[df_rt['return_reason'].isna()]

     return_id order_id product_id return_date return_reason  refund_amount
11    RET00057  O000887      P0598  2025-01-19           NaN         365.91
35    RET02003  O028500      P0426  2024-06-26           NaN         262.51
44    RET00663  O009442      P0172  2024-04-16           NaN        2197.49
49    RET00803  O011341      P0025  2025-01-09           NaN        1587.08
52    RET01737  O024859      P0223  2023-08-27           NaN        1554.77
...        ...      ...        ...         ...           ...            ...
2068  RET01739  O024867      P0539  2024-12-09           NaN         367.99
2075  RET01800  O025648      P0334  2025-01-06           NaN         408.20
2096  RET01753  O024968      P0078  2024-12-05           NaN        2255.60
2120  RET01613  O023018      P0024  2023-08-16           NaN        1938.87
2153  RET01097  O015325      P0504  2025-01-07           NaN         263.46

[126 rows x 6 columns]

In [60]:
df_rt['return_reason'] = df_rt['return_reason'].fillna('Unknown')

In [61]:
df_o = pd.read_csv('orders_clean.csv')

In [62]:
df_o.columns

Index(['order_id', 'customer_id', 'order_date', 'product_id', 'seller_id',
       'quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount',
       'profit', 'order_status', 'shipping_days'],
      dtype='str')

In [63]:
df_rt.columns

Index(['return_id', 'order_id', 'product_id', 'return_date', 'return_reason',
       'refund_amount'],
      dtype='str')

In [28]:
# sales amount is refunded. if he cancelled the order

In [64]:
df_rt = df_rt.merge(df_o[['order_id', 'sales_amount']], on = 'order_id' , how = 'left')

In [65]:
df_rt

,return_id,order_id,product_id,return_date,return_reason,refund_amount,sales_amount
0,RET01729,O024764,P0172,2023-07-21,Size/Fit Issue,2441.66,2441.66
1,RET01379,O019631,P0206,2024-03-09,Wrong Item,NaN,770.10
2,RET00985,O013896,P0419,2023-10-19,Defective,1469.72,1469.72
3,RET00242,O003589,P0339,2025-01-15,Defective,9756.60,9756.60
4,RET00135,O002037,P0172,2023-05-16,Defective,NaN,1953.33
...,...,...,...,...,...,...,...
2088,RET00961,O013636,P0518,2025-01-05,Defective,160.37,160.37
2089,RET00906,O012936,P0402,2025-01-07,Defective,4005.87,4005.87
2090,RET01097,O015325,P0504,2025-01-07,Unknown,263.46,263.46
2091,RET00236,O003544,P0419,2024-07-14,Not As Described,4115.22,4115.22
2092,RET01062,O014816,P0419,2025-01-09,Defective,2792.47,2792.47

In [66]:
df_rt['refund_amount'] = df_rt['refund_amount'].fillna(df_rt['sales_amount'])

In [67]:
df_rt.info()

<class 'pandas.DataFrame'>
RangeIndex: 2093 entries, 0 to 2092
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      2093 non-null   str
 1   order_id       2093 non-null   str
 2   product_id     2093 non-null   str
 3   return_date    2093 non-null   datetime64[us]
 4   return_reason  2093 non-null   str
 5   refund_amount  2093 non-null   float64
 6   sales_amount   2092 non-null   float64
dtypes: datetime64[us](1), float64(2), str(4)
memory usage: 180.5 KB

In [68]:
df_rt[['refund_amount', 'sales_amount']]

      refund_amount  sales_amount
0           2441.66       2441.66
1            770.10        770.10
2           1469.72       1469.72
3           9756.60       9756.60
4           1953.33       1953.33
...             ...           ...
2088         160.37        160.37
2089        4005.87       4005.87
2090         263.46        263.46
2091        4115.22       4115.22
2092        2792.47       2792.47

[2093 rows x 2 columns]

In [69]:
df_rt.info()

<class 'pandas.DataFrame'>
RangeIndex: 2093 entries, 0 to 2092
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      2093 non-null   str
 1   order_id       2093 non-null   str
 2   product_id     2093 non-null   str
 3   return_date    2093 non-null   datetime64[us]
 4   return_reason  2093 non-null   str
 5   refund_amount  2093 non-null   float64
 6   sales_amount   2092 non-null   float64
dtypes: datetime64[us](1), float64(2), str(4)
memory usage: 180.5 KB

In [70]:
df_rt = df_rt[df_rt['order_id'].isin(df_o['order_id'])]

In [71]:
df_rt.info()

<class 'pandas.DataFrame'>
Index: 2092 entries, 0 to 2092
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      2092 non-null   str
 1   order_id       2092 non-null   str
 2   product_id     2092 non-null   str
 3   return_date    2092 non-null   datetime64[us]
 4   return_reason  2092 non-null   str
 5   refund_amount  2092 non-null   float64
 6   sales_amount   2092 non-null   float64
dtypes: datetime64[us](1), float64(2), str(4)
memory usage: 196.8 KB

In [72]:
df_rt.duplicated().sum()

np.int64(0)

In [73]:
df_rt.to_csv('returns_clean.csv', index =  False)