In [2]:
import pandas as pd
import numpy as np

In [3]:
reviews = pd.read_csv('reviews.csv')

In [4]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 19608 entries, 0 to 19607
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    19608 non-null  str
 1   order_id     19608 non-null  str
 2   product_id   19608 non-null  str
 3   customer_id  19608 non-null  str
 4   rating       18831 non-null  str
 5   review_date  19608 non-null  str
 6   review_text  18192 non-null  str
dtypes: str(7)
memory usage: 1.9 MB

In [5]:
reviews.head()

  review_id order_id product_id customer_id rating review_date review_text
0   R010604  O022818      P0511      C02067    3.0  2023-08-11     AVERAGE
1   R009801  O010197      P0587      C01819    5.0  2025-01-11   Excellent
2   R004955  O009108      P0589      C02962    3.0  2023-11-29     Average
3   R007671  O006765      P0122      C04227    4.0  2025-01-21        Good
4   R013835  O026125      P0555      C04787    5.0  2025-01-16   Excellent

In [6]:
df_rw = reviews.copy()

In [7]:
df_rw.info()

<class 'pandas.DataFrame'>
RangeIndex: 19608 entries, 0 to 19607
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    19608 non-null  str
 1   order_id     19608 non-null  str
 2   product_id   19608 non-null  str
 3   customer_id  19608 non-null  str
 4   rating       18831 non-null  str
 5   review_date  19608 non-null  str
 6   review_text  18192 non-null  str
dtypes: str(7)
memory usage: 1.9 MB

In [8]:
df_rw.head()

  review_id order_id product_id customer_id rating review_date review_text
0   R010604  O022818      P0511      C02067    3.0  2023-08-11     AVERAGE
1   R009801  O010197      P0587      C01819    5.0  2025-01-11   Excellent
2   R004955  O009108      P0589      C02962    3.0  2023-11-29     Average
3   R007671  O006765      P0122      C04227    4.0  2025-01-21        Good
4   R013835  O026125      P0555      C04787    5.0  2025-01-16   Excellent

In [9]:
df_rw.duplicated().sum()

np.int64(754)

In [10]:
df_rw = df_rw.drop_duplicates()

In [11]:
df_rw.info()

<class 'pandas.DataFrame'>
Index: 18854 entries, 0 to 19607
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    18854 non-null  str
 1   order_id     18854 non-null  str
 2   product_id   18854 non-null  str
 3   customer_id  18854 non-null  str
 4   rating       18107 non-null  str
 5   review_date  18854 non-null  str
 6   review_text  17488 non-null  str
dtypes: str(7)
memory usage: 2.0 MB

In [12]:
df_rw['review_date'] = pd.to_datetime(df_rw['review_date'], format = 'mixed')

In [13]:
df_rw.info()

<class 'pandas.DataFrame'>
Index: 18854 entries, 0 to 19607
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    18854 non-null  str
 1   order_id     18854 non-null  str
 2   product_id   18854 non-null  str
 3   customer_id  18854 non-null  str
 4   rating       18107 non-null  str
 5   review_date  18854 non-null  datetime64[us]
 6   review_text  17488 non-null  str
dtypes: datetime64[us](1), str(6)
memory usage: 1.8 MB

In [14]:
df_rw['review_text'].unique()

<ArrowStringArray>
[    'AVERAGE',   'Excellent',     'Average',        'Good',        'Poor',
           nan,      ' Poor ',      ' Good ',   'EXCELLENT',        'GOOD',
 ' Excellent ',   ' Average ',   'Very poor',        'POOR',       ' nan ',
 ' Very poor ',         'NAN',   'VERY POOR']
Length: 18, dtype: str

In [15]:
df_rw['review_text'] = df_rw['review_text'].astype(str).str.strip().str.title().replace({'Nan':np.nan})

In [16]:
df_rw['review_text'].unique()

<ArrowStringArray>
['Average', 'Excellent', 'Good', 'Poor', nan, 'Very Poor']
Length: 6, dtype: str

In [17]:
df_rw['rating'].unique()

<ArrowStringArray>
['3.0', '5.0', '4.0', '2.0', nan, '6', '0', '1.0', '10', 'five']
Length: 10, dtype: str

In [18]:
df_rw['rating'] = df_rw['rating'].replace({'five': 5})

In [19]:
df_rw['rating'] = pd.to_numeric(df_rw['rating'])

In [20]:
df_rw['rating'].unique()

array([ 3.,  5.,  4.,  2., nan,  6.,  0.,  1., 10.])

In [21]:
df_rw.loc[~df_rw['rating'].between(1,5), 'rating'] = np.nan

In [22]:
df_rw['rating'].unique()

array([ 3.,  5.,  4.,  2., nan,  1.])

In [23]:
df_rw['rating'].dtypes

dtype('float64')

In [24]:
rating_to_text = {5:'Excellent' , 4:'Good' , 3:'Average', 2:'Poor', 1:'Very Poor'}

In [25]:
text_to_rating = {v: k for k, v in rating_to_text.items()}

In [26]:
df_rw['rating'] = df_rw['rating'].fillna(df_rw['review_text'].map(text_to_rating))

In [27]:
df_rw['review_text'] = df_rw['review_text'].fillna(df_rw['rating'].map(rating_to_text))

In [28]:
df_rw['review_text'].unique()

<ArrowStringArray>
['Average', 'Excellent', 'Good', 'Poor', 'Very Poor', nan]
Length: 6, dtype: str

In [29]:
df_rw['rating'].unique()

array([ 3.,  5.,  4.,  2.,  1., nan])

In [30]:
df_rw.info()

<class 'pandas.DataFrame'>
Index: 18854 entries, 0 to 19607
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    18854 non-null  str
 1   order_id     18854 non-null  str
 2   product_id   18854 non-null  str
 3   customer_id  18854 non-null  str
 4   rating       18770 non-null  float64
 5   review_date  18854 non-null  datetime64[us]
 6   review_text  18770 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 1.7 MB

In [31]:
df_rw['review_text'] = df_rw['review_text'].fillna('Average')

In [32]:
df_rw['rating'] = df_rw['rating'].fillna(3)

In [33]:
df_rw.info()

<class 'pandas.DataFrame'>
Index: 18854 entries, 0 to 19607
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    18854 non-null  str
 1   order_id     18854 non-null  str
 2   product_id   18854 non-null  str
 3   customer_id  18854 non-null  str
 4   rating       18854 non-null  float64
 5   review_date  18854 non-null  datetime64[us]
 6   review_text  18854 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 1.7 MB

In [34]:
df_rw['rating'].unique()

array([3., 5., 4., 2., 1.])

In [35]:
df_rw['rating'] = df_rw['rating'].astype(int)

In [36]:
df_rw.info()

<class 'pandas.DataFrame'>
Index: 18854 entries, 0 to 19607
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    18854 non-null  str
 1   order_id     18854 non-null  str
 2   product_id   18854 non-null  str
 3   customer_id  18854 non-null  str
 4   rating       18854 non-null  int64
 5   review_date  18854 non-null  datetime64[us]
 6   review_text  18854 non-null  str
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 1.7 MB

In [37]:
df_rw.to_csv('reviews_clean.csv', index = False)

In [38]:
df_rw

,review_id,order_id,product_id,customer_id,rating,review_date,review_text
0,R010604,O022818,P0511,C02067,3,2023-08-11,Average
1,R009801,O010197,P0587,C01819,5,2025-01-11,Excellent
2,R004955,O009108,P0589,C02962,3,2023-11-29,Average
3,R007671,O006765,P0122,C04227,4,2025-01-21,Good
4,R013835,O026125,P0555,C04787,5,2025-01-16,Excellent
...,...,...,...,...,...,...,...
19602,R007814,O026882,P0176,C03406,5,2025-01-18,Excellent
19603,R010956,O013930,P0124,C03584,4,2024-10-21,Good
19605,R005193,O029782,P0253,C02104,4,2023-12-04,Good
19606,R012173,O015816,P0332,C04919,5,2025-01-06,Excellent
19607,R000236,O013790,P0431,C04165,3,2024-08-18,Average

In [39]:
df_rw.duplicated().sum()

np.int64(0)