In [1]:
import pandas as pd
import numpy as np

In [2]:
sellers = pd.read_csv('sellers.csv')

In [3]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   seller_id      206 non-null    str
 1   seller_name    206 non-null    str
 2   seller_state   206 non-null    str
 3   seller_rating  197 non-null    float64
 4   join_date      206 non-null    str
dtypes: float64(1), str(4)
memory usage: 15.0 KB

In [4]:
sellers.head()

  seller_id seller_name seller_state  seller_rating   join_date
0     S0079   Seller 79    Karnataka            4.4  2021-02-04
1     S0098   Seller 98    Rajasthan            5.0  2021-03-06
2     S0153  Seller 153    Karnataka            4.8  2021-08-02
3     S0045   Seller 45       Kerala            4.6  2021-07-12
4     S0041   Seller 41    Karnataka            4.5  2020-05-30

In [5]:
sellers.isna().sum()

seller_id        0
seller_name      0
seller_state     0
seller_rating    9
join_date        0
dtype: int64

In [6]:
df_s = sellers.copy()

In [7]:
df_s.info()

<class 'pandas.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   seller_id      206 non-null    str
 1   seller_name    206 non-null    str
 2   seller_state   206 non-null    str
 3   seller_rating  197 non-null    float64
 4   join_date      206 non-null    str
dtypes: float64(1), str(4)
memory usage: 15.0 KB

In [9]:
df_s.duplicated().sum()

np.int64(6)

In [11]:
df_s[df_s.duplicated()]

    seller_id seller_name seller_state  seller_rating     join_date
74      S0108  Seller 108        Delhi            NaN  Oct 29, 2023
125     S0178  Seller 178   Tamil Nadu            4.7  Feb 26, 2022
163     S0050   Seller 50        Delhi            4.6    2021-08-06
177     S0062   Seller 62        Delhi            3.9  Mar 16, 2023
180     S0155  Seller 155    Telangana            4.4    27/05/2021
194     S0026   Seller 26    Karnataka            4.8    2023-11-29

In [12]:
df_s.drop_duplicates()

    seller_id seller_name seller_state  seller_rating     join_date
0       S0079   Seller 79    Karnataka            4.4    2021-02-04
1       S0098   Seller 98    Rajasthan            5.0    2021-03-06
2       S0153  Seller 153    Karnataka            4.8    2021-08-02
3       S0045   Seller 45       Kerala            4.6    2021-07-12
4       S0041   Seller 41    Karnataka            4.5    2020-05-30
..        ...         ...          ...            ...           ...
201     S0134  Seller 134    RAJASTHAN            3.4    18/06/2023
202     S0138  Seller 138       Kerala            4.4    2021-09-10
203     S0073   Seller 73      Gujarat            4.6    2021-02-21
204     S0141  Seller 141      Gujarat            4.1    2023-05-28
205     S0038   Seller 38    Rajasthan            4.4  Aug 27, 2021

[200 rows x 5 columns]

In [13]:
df_s.info()

<class 'pandas.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   seller_id      206 non-null    str
 1   seller_name    206 non-null    str
 2   seller_state   206 non-null    str
 3   seller_rating  197 non-null    float64
 4   join_date      206 non-null    str
dtypes: float64(1), str(4)
memory usage: 15.0 KB

In [14]:
df_o = pd.read_csv('orders_clean.csv')

In [15]:
df_o.columns

Index(['order_id', 'customer_id', 'order_date', 'product_id', 'seller_id',
       'quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount',
       'profit', 'order_status', 'shipping_days'],
      dtype='str')

In [16]:
df_s['seller_state'].unique()

<ArrowStringArray>
[    'Karnataka',     'Rajasthan',        'Kerala',         'Delhi',
 'Uttar Pradesh',       'Gujarat',   'Maharashtra',     'Telangana',
   ' Karnataka ',      ' Kerala ',    'Tamil Nadu',   'West Bengal',
        'KERALA',   ' Telangana ',     'RAJASTHAN',  ' Tamil Nadu ',
   'WEST BENGAL', ' West Bengal ',    'TAMIL NADU', 'UTTAR PRADESH',
 ' Maharashtra ']
Length: 21, dtype: str

In [17]:
df_s['seller_state'] = df_s['seller_state'].astype(str).str.strip().str.title()

In [18]:
df_s['seller_state'].unique()

<ArrowStringArray>
[    'Karnataka',     'Rajasthan',        'Kerala',         'Delhi',
 'Uttar Pradesh',       'Gujarat',   'Maharashtra',     'Telangana',
    'Tamil Nadu',   'West Bengal']
Length: 10, dtype: str

In [19]:
df_s.columns

Index(['seller_id', 'seller_name', 'seller_state', 'seller_rating',
       'join_date'],
      dtype='str')

In [20]:
df_s['seller_rating'].unique()

array([4.4, 5. , 4.8, 4.6, 4.5, 4.3, 3.8, 4.2, nan, 3.7, 9.9, 4. , 3.9,
       4.7, 3.5, 3.4, 3.6, 2.5, 4.1, 4.9, 3.3, 3.1, 3.2, 2.9, 3. ])

In [21]:
df_s[df_s['seller_rating'].isna()]

    seller_id seller_name   seller_state  seller_rating     join_date
8       S0154  Seller 154      Rajasthan            NaN    2021-10-03
23      S0120  Seller 120         Kerala            NaN    2021-05-04
51      S0108  Seller 108          Delhi            NaN  Oct 29, 2023
74      S0108  Seller 108          Delhi            NaN  Oct 29, 2023
76      S0167  Seller 167     Tamil Nadu            NaN    2020-01-09
80      S0094   Seller 94         Kerala            NaN    2023-10-12
111     S0092   Seller 92     Tamil Nadu            NaN    2020-11-04
170     S0182  Seller 182  Uttar Pradesh            NaN    25/06/2020
182     S0087   Seller 87      Telangana            NaN    2020-02-22

In [22]:
df_s['seller_rating'].isna().sum()

np.int64(9)

In [23]:
df_s.loc[~df_s['seller_rating'].between(1,5),'seller_rating'] = np.nan

In [25]:
df_s['seller_rating'] = df_s['seller_rating'].fillna(df_s['seller_rating'].median())

In [26]:
df_s.info()

<class 'pandas.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   seller_id      206 non-null    str
 1   seller_name    206 non-null    str
 2   seller_state   206 non-null    str
 3   seller_rating  206 non-null    float64
 4   join_date      206 non-null    str
dtypes: float64(1), str(4)
memory usage: 15.0 KB

In [27]:
df_s['seller_rating'].unique()

array([4.4, 5. , 4.8, 4.6, 4.5, 4.3, 3.8, 4.2, 3.7, 4. , 3.9, 4.7, 3.5,
       3.4, 3.6, 2.5, 4.1, 4.9, 3.3, 3.1, 3.2, 2.9, 3. ])

In [33]:
df_s['join_date']= pd.to_datetime(df_s['join_date'], format = 'mixed')

In [34]:
df_s.info()

<class 'pandas.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   seller_id      206 non-null    str
 1   seller_name    206 non-null    str
 2   seller_state   206 non-null    str
 3   seller_rating  206 non-null    float64
 4   join_date      206 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 12.9 KB

In [35]:
df_s = df_s.drop_duplicates()

In [36]:
df_s.info()

<class 'pandas.DataFrame'>
Index: 200 entries, 0 to 205
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   seller_id      200 non-null    str
 1   seller_name    200 non-null    str
 2   seller_state   200 non-null    str
 3   seller_rating  200 non-null    float64
 4   join_date      200 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 14.1 KB

In [38]:
df_s.to_csv('sellers_clean.csv', index = False)